name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_SSH_KEY}}
                port: 22
                script: |
                  cd ~/Portfolio_rag
                  git pull
                  cat << 'EOF' > .env
                  GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}
                  EOF
                  cat << 'EOF' > tools/token.json
                  ${{ secrets.GOOGLE_TOKEN_JSON }}
                  EOF
                  cat << 'EOF' > tools/credentials.json
                  ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
                  EOF
                  docker rm -f portfolio-rag || true
                  docker build -t portfolio-rag .
                  docker run -d --name portfolio-rag -p 8000:8000 --env-file .env portfolio-rag

                